// Auto-generated by scripts/build/depVersionsHeader.ts. Do not edit.
// Version values derived from scripts/build/deps/*.ts source definitions.
#ifndef BUN_DEPENDENCY_VERSIONS_H
#define BUN_DEPENDENCY_VERSIONS_H

#ifdef __cplusplus
extern "C" {
#endif

// Dependency versions
#define BUN_DEP_PICOHTTPPARSER "066d2b1e9ab820703db0837a7255d92d30f0c9f5"
#define BUN_DEP_ZLIB_HASH "886098f3f339617b4243b286f5ed364b9989e245"
#define BUN_DEP_ZSTD_HASH "f8745da6ff1ad1e7bab384bd1f9d742439278e99"
#define BUN_DEP_LIBDEFLATE_HASH "c8c56a20f8f621e6a966b716b31f1dedab6a41e3"
#define BUN_DEP_LIBARCHIVE "9525f90ca4bd14c7b335e2f8c84a4607b0af6bdf"
#define BUN_DEP_C_ARES "3ac47ee46edd8ea40370222f91613fc16c434853"
#define BUN_DEP_LOLHTML "e3aa54798602dd27250fafde1b5a66f080046252"
#define BUN_DEP_LSHPACK "8905c024b6d052f083a3d11d0a169b3c2735c8a1"
#define BUN_DEP_MIMALLOC "1beadf9651a7bfdec6b5367c380ecc3fe1c40d1a"
#define BUN_DEP_TINYCC "12882eee073cfe5c7621bcfadf679e1372d4537b"
#define BUN_DEP_BORINGSSL "4f4f5ef8ebc6e23cbf393428f0ab1b526773f7ac"
#define BUN_DEP_WEBKIT "fc9f2fa7272fec64905df6a9c78e15d7912f14ca"
#define BUN_DEP_BUN_VERSION "1.3.11"
#define BUN_DEP_NODEJS_COMPAT_VERSION "24.3.0"
#define BUN_DEP_UWS "d7e13bef85213653be3f757ab849fc69104cc409"
#define BUN_DEP_USOCKETS "d7e13bef85213653be3f757ab849fc69104cc409"
#define BUN_DEP_ZIG "c031cbebf5b063210473ff5204a24ebfb2492c72"

// C string constants for easy access
static const char* const BUN_VERSION_PICOHTTPPARSER = "066d2b1e9ab820703db0837a7255d92d30f0c9f5";
static const char* const BUN_VERSION_ZLIB_HASH = "886098f3f339617b4243b286f5ed364b9989e245";
static const char* const BUN_VERSION_ZSTD_HASH = "f8745da6ff1ad1e7bab384bd1f9d742439278e99";
static const char* const BUN_VERSION_LIBDEFLATE_HASH = "c8c56a20f8f621e6a966b716b31f1dedab6a41e3";
static const char* const BUN_VERSION_LIBARCHIVE = "9525f90ca4bd14c7b335e2f8c84a4607b0af6bdf";
static const char* const BUN_VERSION_C_ARES = "3ac47ee46edd8ea40370222f91613fc16c434853";
static const char* const BUN_VERSION_LOLHTML = "e3aa54798602dd27250fafde1b5a66f080046252";
static const char* const BUN_VERSION_LSHPACK = "8905c024b6d052f083a3d11d0a169b3c2735c8a1";
static const char* const BUN_VERSION_MIMALLOC = "1beadf9651a7bfdec6b5367c380ecc3fe1c40d1a";
static const char* const BUN_VERSION_TINYCC = "12882eee073cfe5c7621bcfadf679e1372d4537b";
static const char* const BUN_VERSION_BORINGSSL = "4f4f5ef8ebc6e23cbf393428f0ab1b526773f7ac";
static const char* const BUN_VERSION_WEBKIT = "fc9f2fa7272fec64905df6a9c78e15d7912f14ca";
static const char* const BUN_VERSION_BUN_VERSION = "1.3.11";
static const char* const BUN_VERSION_NODEJS_COMPAT_VERSION = "24.3.0";
static const char* const BUN_VERSION_UWS = "d7e13bef85213653be3f757ab849fc69104cc409";
static const char* const BUN_VERSION_USOCKETS = "d7e13bef85213653be3f757ab849fc69104cc409";
static const char* const BUN_VERSION_ZIG = "c031cbebf5b063210473ff5204a24ebfb2492c72";

#ifdef __cplusplus
}
#endif

#endif // BUN_DEPENDENCY_VERSIONS_H
