// GENERATED TEMP FILE - DO NOT EDIT
// generated by /home/fanmi/workspace/bun/src/codegen/bundle-modules.ts

declare module "module" {
  global {
    interface PropertyDescriptor {
      __proto__?: any;
    }

    interface Function {
      readonly $call: Function.prototype["call"];
      readonly $apply: Function.prototype["apply"];
    }

    namespace NodeJS {
      interface Require {

        (id: "bun"): typeof import("bun");
        (id: "bun:test"): typeof import("bun:test");
        (id: "bun:jsc"): typeof import("bun:jsc");
        (id: "bun:ffi"): typeof import("/home/fanmi/workspace/bun/src/js/bun/ffi.ts").default;
        (id: "bun:sql"): typeof import("/home/fanmi/workspace/bun/src/js/bun/sql.ts").default;
        (id: "bun:sqlite"): typeof import("/home/fanmi/workspace/bun/src/js/bun/sqlite.ts").default;
        (id: "internal/abort_listener"): typeof import("/home/fanmi/workspace/bun/src/js/internal/abort_listener.ts").default;
        (id: "internal/assert/assertion_error"): typeof import("/home/fanmi/workspace/bun/src/js/internal/assert/assertion_error.ts").default;
        (id: "internal/assert/calltracker"): typeof import("/home/fanmi/workspace/bun/src/js/internal/assert/calltracker.ts").default;
        (id: "internal/assert/myers_diff"): typeof import("/home/fanmi/workspace/bun/src/js/internal/assert/myers_diff.ts").default;
        (id: "internal/assert/utils"): typeof import("/home/fanmi/workspace/bun/src/js/internal/assert/utils.ts").default;
        (id: "internal/buffer"): typeof import("/home/fanmi/workspace/bun/src/js/internal/buffer.ts").default;
        (id: "internal/cluster/RoundRobinHandle"): typeof import("/home/fanmi/workspace/bun/src/js/internal/cluster/RoundRobinHandle.ts").default;
        (id: "internal/cluster/Worker"): typeof import("/home/fanmi/workspace/bun/src/js/internal/cluster/Worker.ts").default;
        (id: "internal/cluster/child"): typeof import("/home/fanmi/workspace/bun/src/js/internal/cluster/child.ts").default;
        (id: "internal/cluster/isPrimary"): typeof import("/home/fanmi/workspace/bun/src/js/internal/cluster/isPrimary.ts").default;
        (id: "internal/cluster/primary"): typeof import("/home/fanmi/workspace/bun/src/js/internal/cluster/primary.ts").default;
        (id: "internal/crypto/x509"): typeof import("/home/fanmi/workspace/bun/src/js/internal/crypto/x509.ts").default;
        (id: "internal/debugger"): typeof import("/home/fanmi/workspace/bun/src/js/internal/debugger.ts").default;
        (id: "internal/errors"): typeof import("/home/fanmi/workspace/bun/src/js/internal/errors.ts").default;
        (id: "internal/fifo"): typeof import("/home/fanmi/workspace/bun/src/js/internal/fifo.ts").default;
        (id: "internal/fixed_queue"): typeof import("/home/fanmi/workspace/bun/src/js/internal/fixed_queue.ts").default;
        (id: "internal/freelist"): typeof import("/home/fanmi/workspace/bun/src/js/internal/freelist.ts").default;
        (id: "internal/fs/cp-sync"): typeof import("/home/fanmi/workspace/bun/src/js/internal/fs/cp-sync.ts").default;
        (id: "internal/fs/cp"): typeof import("/home/fanmi/workspace/bun/src/js/internal/fs/cp.ts").default;
        (id: "internal/fs/glob"): typeof import("/home/fanmi/workspace/bun/src/js/internal/fs/glob.ts").default;
        (id: "internal/fs/streams"): typeof import("/home/fanmi/workspace/bun/src/js/internal/fs/streams.ts").default;
        (id: "internal/html"): typeof import("/home/fanmi/workspace/bun/src/js/internal/html.ts").default;
        (id: "internal/http"): typeof import("/home/fanmi/workspace/bun/src/js/internal/http.ts").default;
        (id: "internal/http/FakeSocket"): typeof import("/home/fanmi/workspace/bun/src/js/internal/http/FakeSocket.ts").default;
        (id: "internal/linkedlist"): typeof import("/home/fanmi/workspace/bun/src/js/internal/linkedlist.ts").default;
        (id: "internal/net/isIP"): typeof import("/home/fanmi/workspace/bun/src/js/internal/net/isIP.ts").default;
        (id: "internal/perf_hooks/monitorEventLoopDelay"): typeof import("/home/fanmi/workspace/bun/src/js/internal/perf_hooks/monitorEventLoopDelay.ts").default;
        (id: "internal/primordials"): typeof import("/home/fanmi/workspace/bun/src/js/internal/primordials.js").default;
        (id: "internal/promisify"): typeof import("/home/fanmi/workspace/bun/src/js/internal/promisify.ts").default;
        (id: "internal/shared"): typeof import("/home/fanmi/workspace/bun/src/js/internal/shared.ts").default;
        (id: "internal/sql/errors"): typeof import("/home/fanmi/workspace/bun/src/js/internal/sql/errors.ts").default;
        (id: "internal/sql/mysql"): typeof import("/home/fanmi/workspace/bun/src/js/internal/sql/mysql.ts").default;
        (id: "internal/sql/postgres"): typeof import("/home/fanmi/workspace/bun/src/js/internal/sql/postgres.ts").default;
        (id: "internal/sql/query"): typeof import("/home/fanmi/workspace/bun/src/js/internal/sql/query.ts").default;
        (id: "internal/sql/shared"): typeof import("/home/fanmi/workspace/bun/src/js/internal/sql/shared.ts").default;
        (id: "internal/sql/sqlite"): typeof import("/home/fanmi/workspace/bun/src/js/internal/sql/sqlite.ts").default;
        (id: "internal/stream/promises"): typeof import("/home/fanmi/workspace/bun/src/js/internal/stream.promises.ts").default;
        (id: "internal/stream"): typeof import("/home/fanmi/workspace/bun/src/js/internal/stream.ts").default;
        (id: "internal/streams/add-abort-signal"): typeof import("/home/fanmi/workspace/bun/src/js/internal/streams/add-abort-signal.ts").default;
        (id: "internal/streams/compose"): typeof import("/home/fanmi/workspace/bun/src/js/internal/streams/compose.ts").default;
        (id: "internal/streams/destroy"): typeof import("/home/fanmi/workspace/bun/src/js/internal/streams/destroy.ts").default;
        (id: "internal/streams/duplex"): typeof import("/home/fanmi/workspace/bun/src/js/internal/streams/duplex.ts").default;
        (id: "internal/streams/duplexify"): typeof import("/home/fanmi/workspace/bun/src/js/internal/streams/duplexify.ts").default;
        (id: "internal/streams/duplexpair"): typeof import("/home/fanmi/workspace/bun/src/js/internal/streams/duplexpair.ts").default;
        (id: "internal/streams/end-of-stream"): typeof import("/home/fanmi/workspace/bun/src/js/internal/streams/end-of-stream.ts").default;
        (id: "internal/streams/from"): typeof import("/home/fanmi/workspace/bun/src/js/internal/streams/from.ts").default;
        (id: "internal/streams/lazy_transform"): typeof import("/home/fanmi/workspace/bun/src/js/internal/streams/lazy_transform.ts").default;
        (id: "internal/streams/legacy"): typeof import("/home/fanmi/workspace/bun/src/js/internal/streams/legacy.ts").default;
        (id: "internal/streams/native-readable"): typeof import("/home/fanmi/workspace/bun/src/js/internal/streams/native-readable.ts").default;
        (id: "internal/streams/operators"): typeof import("/home/fanmi/workspace/bun/src/js/internal/streams/operators.ts").default;
        (id: "internal/streams/passthrough"): typeof import("/home/fanmi/workspace/bun/src/js/internal/streams/passthrough.ts").default;
        (id: "internal/streams/pipeline"): typeof import("/home/fanmi/workspace/bun/src/js/internal/streams/pipeline.ts").default;
        (id: "internal/streams/readable"): typeof import("/home/fanmi/workspace/bun/src/js/internal/streams/readable.ts").default;
        (id: "internal/streams/state"): typeof import("/home/fanmi/workspace/bun/src/js/internal/streams/state.ts").default;
        (id: "internal/streams/transform"): typeof import("/home/fanmi/workspace/bun/src/js/internal/streams/transform.ts").default;
        (id: "internal/streams/utils"): typeof import("/home/fanmi/workspace/bun/src/js/internal/streams/utils.ts").default;
        (id: "internal/streams/writable"): typeof import("/home/fanmi/workspace/bun/src/js/internal/streams/writable.ts").default;
        (id: "internal/timers"): typeof import("/home/fanmi/workspace/bun/src/js/internal/timers.ts").default;
        (id: "internal/tls"): typeof import("/home/fanmi/workspace/bun/src/js/internal/tls.ts").default;
        (id: "internal/tty"): typeof import("/home/fanmi/workspace/bun/src/js/internal/tty.ts").default;
        (id: "internal/url"): typeof import("/home/fanmi/workspace/bun/src/js/internal/url.ts").default;
        (id: "internal/util/colors"): typeof import("/home/fanmi/workspace/bun/src/js/internal/util/colors.ts").default;
        (id: "internal/util/deprecate"): typeof import("/home/fanmi/workspace/bun/src/js/internal/util/deprecate.ts").default;
        (id: "internal/util/inspect"): typeof import("/home/fanmi/workspace/bun/src/js/internal/util/inspect.js").default;
        (id: "internal/util/mime"): typeof import("/home/fanmi/workspace/bun/src/js/internal/util/mime.ts").default;
        (id: "internal/validators"): typeof import("/home/fanmi/workspace/bun/src/js/internal/validators.ts").default;
        (id: "internal/webstreams_adapters"): typeof import("/home/fanmi/workspace/bun/src/js/internal/webstreams_adapters.ts").default;
        (id: "node:_http2_upgrade"): typeof import("/home/fanmi/workspace/bun/src/js/node/_http2_upgrade.ts").default;
        (id: "node:_http_agent"): typeof import("/home/fanmi/workspace/bun/src/js/node/_http_agent.ts").default;
        (id: "node:_http_client"): typeof import("/home/fanmi/workspace/bun/src/js/node/_http_client.ts").default;
        (id: "node:_http_common"): typeof import("/home/fanmi/workspace/bun/src/js/node/_http_common.ts").default;
        (id: "node:_http_incoming"): typeof import("/home/fanmi/workspace/bun/src/js/node/_http_incoming.ts").default;
        (id: "node:_http_outgoing"): typeof import("/home/fanmi/workspace/bun/src/js/node/_http_outgoing.ts").default;
        (id: "node:_http_server"): typeof import("/home/fanmi/workspace/bun/src/js/node/_http_server.ts").default;
        (id: "node:_stream_duplex"): typeof import("/home/fanmi/workspace/bun/src/js/node/_stream_duplex.ts").default;
        (id: "node:_stream_passthrough"): typeof import("/home/fanmi/workspace/bun/src/js/node/_stream_passthrough.ts").default;
        (id: "node:_stream_readable"): typeof import("/home/fanmi/workspace/bun/src/js/node/_stream_readable.ts").default;
        (id: "node:_stream_transform"): typeof import("/home/fanmi/workspace/bun/src/js/node/_stream_transform.ts").default;
        (id: "node:_stream_wrap"): typeof import("/home/fanmi/workspace/bun/src/js/node/_stream_wrap.ts").default;
        (id: "node:_stream_writable"): typeof import("/home/fanmi/workspace/bun/src/js/node/_stream_writable.ts").default;
        (id: "node:_tls_common"): typeof import("/home/fanmi/workspace/bun/src/js/node/_tls_common.ts").default;
        (id: "node:assert/strict"): typeof import("/home/fanmi/workspace/bun/src/js/node/assert.strict.ts").default;
        (id: "node:assert"): typeof import("/home/fanmi/workspace/bun/src/js/node/assert.ts").default;
        (id: "node:async_hooks"): typeof import("/home/fanmi/workspace/bun/src/js/node/async_hooks.ts").default;
        (id: "node:child_process"): typeof import("/home/fanmi/workspace/bun/src/js/node/child_process.ts").default;
        (id: "node:cluster"): typeof import("/home/fanmi/workspace/bun/src/js/node/cluster.ts").default;
        (id: "node:console"): typeof import("/home/fanmi/workspace/bun/src/js/node/console.ts").default;
        (id: "node:crypto"): typeof import("/home/fanmi/workspace/bun/src/js/node/crypto.ts").default;
        (id: "node:dgram"): typeof import("/home/fanmi/workspace/bun/src/js/node/dgram.ts").default;
        (id: "node:diagnostics_channel"): typeof import("/home/fanmi/workspace/bun/src/js/node/diagnostics_channel.ts").default;
        (id: "node:dns/promises"): typeof import("/home/fanmi/workspace/bun/src/js/node/dns.promises.ts").default;
        (id: "node:dns"): typeof import("/home/fanmi/workspace/bun/src/js/node/dns.ts").default;
        (id: "node:domain"): typeof import("/home/fanmi/workspace/bun/src/js/node/domain.ts").default;
        (id: "node:events"): typeof import("/home/fanmi/workspace/bun/src/js/node/events.ts").default;
        (id: "node:fs/promises"): typeof import("/home/fanmi/workspace/bun/src/js/node/fs.promises.ts").default;
        (id: "node:fs"): typeof import("/home/fanmi/workspace/bun/src/js/node/fs.ts").default;
        (id: "node:http"): typeof import("/home/fanmi/workspace/bun/src/js/node/http.ts").default;
        (id: "node:http2"): typeof import("/home/fanmi/workspace/bun/src/js/node/http2.ts").default;
        (id: "node:https"): typeof import("/home/fanmi/workspace/bun/src/js/node/https.ts").default;
        (id: "node:inspector/promises"): typeof import("/home/fanmi/workspace/bun/src/js/node/inspector.promises.ts").default;
        (id: "node:inspector"): typeof import("/home/fanmi/workspace/bun/src/js/node/inspector.ts").default;
        (id: "node:net"): typeof import("/home/fanmi/workspace/bun/src/js/node/net.ts").default;
        (id: "node:os"): typeof import("/home/fanmi/workspace/bun/src/js/node/os.ts").default;
        (id: "node:path/posix"): typeof import("/home/fanmi/workspace/bun/src/js/node/path.posix.ts").default;
        (id: "node:path"): typeof import("/home/fanmi/workspace/bun/src/js/node/path.ts").default;
        (id: "node:path/win32"): typeof import("/home/fanmi/workspace/bun/src/js/node/path.win32.ts").default;
        (id: "node:perf_hooks"): typeof import("/home/fanmi/workspace/bun/src/js/node/perf_hooks.ts").default;
        (id: "node:punycode"): typeof import("/home/fanmi/workspace/bun/src/js/node/punycode.ts").default;
        (id: "node:querystring"): typeof import("/home/fanmi/workspace/bun/src/js/node/querystring.ts").default;
        (id: "node:readline/promises"): typeof import("/home/fanmi/workspace/bun/src/js/node/readline.promises.ts").default;
        (id: "node:readline"): typeof import("/home/fanmi/workspace/bun/src/js/node/readline.ts").default;
        (id: "node:repl"): typeof import("/home/fanmi/workspace/bun/src/js/node/repl.ts").default;
        (id: "node:stream/consumers"): typeof import("/home/fanmi/workspace/bun/src/js/node/stream.consumers.ts").default;
        (id: "node:stream/promises"): typeof import("/home/fanmi/workspace/bun/src/js/node/stream.promises.ts").default;
        (id: "node:stream"): typeof import("/home/fanmi/workspace/bun/src/js/node/stream.ts").default;
        (id: "node:stream/web"): typeof import("/home/fanmi/workspace/bun/src/js/node/stream.web.ts").default;
        (id: "node:test"): typeof import("/home/fanmi/workspace/bun/src/js/node/test.ts").default;
        (id: "node:timers/promises"): typeof import("/home/fanmi/workspace/bun/src/js/node/timers.promises.ts").default;
        (id: "node:timers"): typeof import("/home/fanmi/workspace/bun/src/js/node/timers.ts").default;
        (id: "node:tls"): typeof import("/home/fanmi/workspace/bun/src/js/node/tls.ts").default;
        (id: "node:trace_events"): typeof import("/home/fanmi/workspace/bun/src/js/node/trace_events.ts").default;
        (id: "node:tty"): typeof import("/home/fanmi/workspace/bun/src/js/node/tty.ts").default;
        (id: "node:url"): typeof import("/home/fanmi/workspace/bun/src/js/node/url.ts").default;
        (id: "node:util"): typeof import("/home/fanmi/workspace/bun/src/js/node/util.ts").default;
        (id: "node:v8"): typeof import("/home/fanmi/workspace/bun/src/js/node/v8.ts").default;
        (id: "node:vm"): typeof import("/home/fanmi/workspace/bun/src/js/node/vm.ts").default;
        (id: "node:wasi"): typeof import("/home/fanmi/workspace/bun/src/js/node/wasi.ts").default;
        (id: "node:worker_threads"): typeof import("/home/fanmi/workspace/bun/src/js/node/worker_threads.ts").default;
        (id: "node:zlib"): typeof import("/home/fanmi/workspace/bun/src/js/node/zlib.ts").default;
        (id: "isomorphic-fetch"): typeof import("/home/fanmi/workspace/bun/src/js/thirdparty/isomorphic-fetch.ts").default;
        (id: "node-fetch"): typeof import("/home/fanmi/workspace/bun/src/js/thirdparty/node-fetch.ts").default;
        (id: "undici"): typeof import("/home/fanmi/workspace/bun/src/js/thirdparty/undici.js").default;
        (id: "vercel_fetch"): typeof import("/home/fanmi/workspace/bun/src/js/thirdparty/vercel_fetch.js").default;
        (id: "ws"): typeof import("/home/fanmi/workspace/bun/src/js/thirdparty/ws.js").default;
        (id: "bun:internal-for-testing"): typeof import("/home/fanmi/workspace/bun/src/js/internal-for-testing.ts").default;

      }
    }
  }
}

declare function $inheritsBlob(value: any): value is Blob;
declare function $inheritsReadableStream(value: any): value is ReadableStream;
declare function $inheritsWritableStream(value: any): value is WritableStream;
declare function $inheritsTransformStream(value: any): value is TransformStream;
declare function $inheritsArrayBuffer(value: any): value is ArrayBuffer;
declare function $inheritsCompressionStream(value: any): value is CompressionStream;
declare function $inheritsDecompressionStream(value: any): value is DecompressionStream;
