#pragma once
// File generated via `create-hash-table.ts`
static constinit const struct CompactHashIndex processBindingFsTableIndex[136] = {
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 5, 134 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 34, -1 },
    { 0, 128 },
    { -1, -1 },
    { -1, -1 },
    { 39, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 26, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 4, -1 },
    { 12, -1 },
    { -1, -1 },
    { -1, -1 },
    { 33, -1 },
    { 9, -1 },
    { 15, 135 },
    { 6, -1 },
    { -1, -1 },
    { -1, -1 },
    { 19, -1 },
    { 44, -1 },
    { -1, -1 },
    { 29, -1 },
    { -1, -1 },
    { 8, 130 },
    { -1, -1 },
    { -1, -1 },
    { 46, -1 },
    { -1, -1 },
    { 18, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 38, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 21, -1 },
    { -1, -1 },
    { 7, -1 },
    { -1, -1 },
    { 35, -1 },
    { 45, -1 },
    { -1, -1 },
    { 43, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 41, -1 },
    { -1, -1 },
    { 31, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 23, -1 },
    { 36, -1 },
    { -1, -1 },
    { 30, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 32, 133 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 20, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 11, 131 },
    { 3, -1 },
    { 37, -1 },
    { 47, -1 },
    { 24, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 27, -1 },
    { 10, 129 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 1, 132 },
    { 17, -1 },
    { 13, -1 },
    { 2, -1 },
    { 14, -1 },
    { 16, -1 },
    { 22, -1 },
    { 25, -1 },
    { 28, -1 },
    { 40, -1 },
    { 42, -1 },
    { 48, -1 },
};

static constinit const struct HashTableValue processBindingFsTableValues[49] = {
   { "access"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_access, 1 } },
   { "bigintStatFsValues"_s, static_cast<unsigned>(PropertyAttribute::PropertyCallback), NoIntrinsic, { HashTableValue::LazyPropertyType, ProcessBindingFs_bigintStatFsValues } },
   { "bigintStatValues"_s, static_cast<unsigned>(PropertyAttribute::PropertyCallback), NoIntrinsic, { HashTableValue::LazyPropertyType, ProcessBindingFs_bigintStatValues } },
   { "chmod"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_chmod, 1 } },
   { "chown"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_chown, 1 } },
   { "close"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_close, 1 } },
   { "copyFile"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_copyFile, 1 } },
   { "cpSyncCheckPaths"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_cpSyncCheckPaths, 1 } },
   { "existsSync"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_existsSync, 1 } },
   { "fchmod"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_fchmod, 1 } },
   { "fchown"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_fchown, 1 } },
   { "fdatasync"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_fdatasync, 1 } },
   { "fstat"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_fstat, 1 } },
   { "fsync"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_fsync, 1 } },
   { "ftruncate"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_ftruncate, 1 } },
   { "futimes"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_futimes, 1 } },
   { "getFormatOfExtensionlessFile"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_getFormatOfExtensionlessFile, 1 } },
   { "internalModuleStat"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_internalModuleStat, 1 } },
   { "kFsStatsFieldsNumber"_s, static_cast<unsigned>(PropertyAttribute::ConstantInteger), NoIntrinsic, { HashTableValue::ConstantType, 18 } },
   { "lchown"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_lchown, 1 } },
   { "legacyMainResolve"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_legacyMainResolve, 1 } },
   { "link"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_link, 1 } },
   { "lstat"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_lstat, 1 } },
   { "lutimes"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_lutimes, 1 } },
   { "mkdir"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_mkdir, 1 } },
   { "mkdtemp"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_mkdtemp, 1 } },
   { "open"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_open, 1 } },
   { "openFileHandle"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_openFileHandle, 1 } },
   { "read"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_read, 1 } },
   { "readBuffers"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_readBuffers, 1 } },
   { "readdir"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_readdir, 1 } },
   { "readFileUtf8"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_readFileUtf8, 1 } },
   { "readlink"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_readlink, 1 } },
   { "realpath"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_realpath, 1 } },
   { "rename"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_rename, 1 } },
   { "rmdir"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_rmdir, 1 } },
   { "rmSync"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_rmSync, 1 } },
   { "stat"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_stat, 1 } },
   { "statfs"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_statfs, 1 } },
   { "statFsValues"_s, static_cast<unsigned>(PropertyAttribute::PropertyCallback), NoIntrinsic, { HashTableValue::LazyPropertyType, ProcessBindingFs_statFsValues } },
   { "statValues"_s, static_cast<unsigned>(PropertyAttribute::PropertyCallback), NoIntrinsic, { HashTableValue::LazyPropertyType, ProcessBindingFs_statValues } },
   { "StatWatcher"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_StatWatcher, 1 } },
   { "symlink"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_symlink, 1 } },
   { "unlink"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_unlink, 1 } },
   { "utimes"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_utimes, 1 } },
   { "writeBuffer"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_writeBuffer, 1 } },
   { "writeBuffers"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_writeBuffers, 1 } },
   { "writeFileUtf8"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_writeFileUtf8, 1 } },
   { "writeString"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Fs_writeString, 1 } },
};

static constinit const struct HashTable processBindingFsTable =
    { 49, 127, false, nullptr, processBindingFsTableValues, processBindingFsTableIndex };
