// Generated by: src/codegen/generate-node-errors.ts
// Input:        src/bun.js/bindings/ErrorCode.ts

// Global error code functions for TypeScript

/**
 * Construct an {@link Error Error} with the `"ABORT_ERR"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ABORT_ERR"` in builtins.d.ts.
 */
declare function $ABORT_ERR(message: string): Error & { name: "AbortError", code: "ABORT_ERR" };

/**
 * Construct an {@link Error Error} with the `"ERR_ACCESS_DENIED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_ACCESS_DENIED"` in builtins.d.ts.
 */
declare function $ERR_ACCESS_DENIED(message: string): Error & { code: "ERR_ACCESS_DENIED" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_ARG_NOT_ITERABLE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_ARG_NOT_ITERABLE"` in builtins.d.ts.
 */
declare function $ERR_ARG_NOT_ITERABLE(message: string): TypeError & { code: "ERR_ARG_NOT_ITERABLE" };

/**
 * Construct an {@link Error Error} with the `"ERR_ASSERTION"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_ASSERTION"` in builtins.d.ts.
 */
declare function $ERR_ASSERTION(message: string): Error & { code: "ERR_ASSERTION" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_BODY_ALREADY_USED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_BODY_ALREADY_USED"` in builtins.d.ts.
 */
declare function $ERR_BODY_ALREADY_USED(message: string): TypeError & { code: "ERR_BODY_ALREADY_USED" };

/**
 * Construct an {@link Error Error} with the `"ERR_BORINGSSL"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_BORINGSSL"` in builtins.d.ts.
 */
declare function $ERR_BORINGSSL(message: string): Error & { code: "ERR_BORINGSSL" };

/**
 * Construct an {@link Error Error} with the `"ERR_ZSTD"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_ZSTD"` in builtins.d.ts.
 */
declare function $ERR_ZSTD(message: string): Error & { code: "ERR_ZSTD" };

/**
 * Construct an {@link Error Error} with the `"ERR_BUFFER_CONTEXT_NOT_AVAILABLE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_BUFFER_CONTEXT_NOT_AVAILABLE"` in builtins.d.ts.
 */
declare function $ERR_BUFFER_CONTEXT_NOT_AVAILABLE(message: string): Error & { code: "ERR_BUFFER_CONTEXT_NOT_AVAILABLE" };

/**
 * Construct an {@link Error Error} with the `"ERR_CLOSED_MESSAGE_PORT"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CLOSED_MESSAGE_PORT"` in builtins.d.ts.
 */
declare function $ERR_CLOSED_MESSAGE_PORT(message: string): Error & { code: "ERR_CLOSED_MESSAGE_PORT" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_CONSOLE_WRITABLE_STREAM"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CONSOLE_WRITABLE_STREAM"` in builtins.d.ts.
 */
declare function $ERR_CONSOLE_WRITABLE_STREAM(message: string): TypeError & { code: "ERR_CONSOLE_WRITABLE_STREAM" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_CONSTRUCT_CALL_INVALID"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CONSTRUCT_CALL_INVALID"` in builtins.d.ts.
 */
declare function $ERR_CONSTRUCT_CALL_INVALID(message: string): TypeError & { code: "ERR_CONSTRUCT_CALL_INVALID" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_CONSTRUCT_CALL_REQUIRED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CONSTRUCT_CALL_REQUIRED"` in builtins.d.ts.
 */
declare function $ERR_CONSTRUCT_CALL_REQUIRED(message: string): TypeError & { code: "ERR_CONSTRUCT_CALL_REQUIRED" };

/**
 * Construct an {@link Error Error} with the `"ERR_CRYPTO_CUSTOM_ENGINE_NOT_SUPPORTED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CRYPTO_CUSTOM_ENGINE_NOT_SUPPORTED"` in builtins.d.ts.
 */
declare function $ERR_CRYPTO_CUSTOM_ENGINE_NOT_SUPPORTED(message: string): Error & { code: "ERR_CRYPTO_CUSTOM_ENGINE_NOT_SUPPORTED" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_CRYPTO_ECDH_INVALID_FORMAT"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CRYPTO_ECDH_INVALID_FORMAT"` in builtins.d.ts.
 */
declare function $ERR_CRYPTO_ECDH_INVALID_FORMAT(message: string): TypeError & { code: "ERR_CRYPTO_ECDH_INVALID_FORMAT" };

/**
 * Construct an {@link Error Error} with the `"ERR_CRYPTO_ECDH_INVALID_PUBLIC_KEY"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CRYPTO_ECDH_INVALID_PUBLIC_KEY"` in builtins.d.ts.
 */
declare function $ERR_CRYPTO_ECDH_INVALID_PUBLIC_KEY(message: string): Error & { code: "ERR_CRYPTO_ECDH_INVALID_PUBLIC_KEY" };

/**
 * Construct an {@link Error Error} with the `"ERR_CRYPTO_HASH_FINALIZED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CRYPTO_HASH_FINALIZED"` in builtins.d.ts.
 */
declare function $ERR_CRYPTO_HASH_FINALIZED(message: string): Error & { code: "ERR_CRYPTO_HASH_FINALIZED" };

/**
 * Construct an {@link Error Error} with the `"ERR_CRYPTO_HASH_UPDATE_FAILED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CRYPTO_HASH_UPDATE_FAILED"` in builtins.d.ts.
 */
declare function $ERR_CRYPTO_HASH_UPDATE_FAILED(message: string): Error & { code: "ERR_CRYPTO_HASH_UPDATE_FAILED" };

/**
 * Construct an {@link Error Error} with the `"ERR_CRYPTO_INCOMPATIBLE_KEY_OPTIONS"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CRYPTO_INCOMPATIBLE_KEY_OPTIONS"` in builtins.d.ts.
 */
declare function $ERR_CRYPTO_INCOMPATIBLE_KEY_OPTIONS(message: string): Error & { code: "ERR_CRYPTO_INCOMPATIBLE_KEY_OPTIONS" };

/**
 * Construct an {@link Error Error} with the `"ERR_CRYPTO_INITIALIZATION_FAILED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CRYPTO_INITIALIZATION_FAILED"` in builtins.d.ts.
 */
declare function $ERR_CRYPTO_INITIALIZATION_FAILED(message: string): Error & { code: "ERR_CRYPTO_INITIALIZATION_FAILED" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_CRYPTO_INVALID_AUTH_TAG"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CRYPTO_INVALID_AUTH_TAG"` in builtins.d.ts.
 */
declare function $ERR_CRYPTO_INVALID_AUTH_TAG(message: string): TypeError & { code: "ERR_CRYPTO_INVALID_AUTH_TAG" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_CRYPTO_INVALID_COUNTER"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CRYPTO_INVALID_COUNTER"` in builtins.d.ts.
 */
declare function $ERR_CRYPTO_INVALID_COUNTER(message: string): TypeError & { code: "ERR_CRYPTO_INVALID_COUNTER" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_CRYPTO_INVALID_CURVE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CRYPTO_INVALID_CURVE"` in builtins.d.ts.
 */
declare function $ERR_CRYPTO_INVALID_CURVE(message: string): TypeError & { code: "ERR_CRYPTO_INVALID_CURVE" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_CRYPTO_INVALID_DIGEST"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CRYPTO_INVALID_DIGEST"` in builtins.d.ts.
 */
declare function $ERR_CRYPTO_INVALID_DIGEST(message: string): TypeError & { code: "ERR_CRYPTO_INVALID_DIGEST" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_CRYPTO_INVALID_IV"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CRYPTO_INVALID_IV"` in builtins.d.ts.
 */
declare function $ERR_CRYPTO_INVALID_IV(message: string): TypeError & { code: "ERR_CRYPTO_INVALID_IV" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_CRYPTO_INVALID_JWK"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CRYPTO_INVALID_JWK"` in builtins.d.ts.
 */
declare function $ERR_CRYPTO_INVALID_JWK(message: string): TypeError & { code: "ERR_CRYPTO_INVALID_JWK" };

/**
 * Construct an {@link RangeError RangeError} with the `"ERR_CRYPTO_INVALID_KEYLEN"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CRYPTO_INVALID_KEYLEN"` in builtins.d.ts.
 */
declare function $ERR_CRYPTO_INVALID_KEYLEN(message: string): RangeError & { code: "ERR_CRYPTO_INVALID_KEYLEN" };

/**
 * Construct an {@link RangeError RangeError} with the `"ERR_CRYPTO_INVALID_KEYPAIR"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CRYPTO_INVALID_KEYPAIR"` in builtins.d.ts.
 */
declare function $ERR_CRYPTO_INVALID_KEYPAIR(message: string): RangeError & { code: "ERR_CRYPTO_INVALID_KEYPAIR" };

/**
 * Construct an {@link RangeError RangeError} with the `"ERR_CRYPTO_INVALID_KEYTYPE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CRYPTO_INVALID_KEYTYPE"` in builtins.d.ts.
 */
declare function $ERR_CRYPTO_INVALID_KEYTYPE(message: string): RangeError & { code: "ERR_CRYPTO_INVALID_KEYTYPE" };

/**
 * Construct an {@link RangeError RangeError} with the `"ERR_CRYPTO_INVALID_MESSAGELEN"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CRYPTO_INVALID_MESSAGELEN"` in builtins.d.ts.
 */
declare function $ERR_CRYPTO_INVALID_MESSAGELEN(message: string): RangeError & { code: "ERR_CRYPTO_INVALID_MESSAGELEN" };

/**
 * Construct an {@link RangeError RangeError} with the `"ERR_CRYPTO_INVALID_SCRYPT_PARAMS"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CRYPTO_INVALID_SCRYPT_PARAMS"` in builtins.d.ts.
 */
declare function $ERR_CRYPTO_INVALID_SCRYPT_PARAMS(message: string): RangeError & { code: "ERR_CRYPTO_INVALID_SCRYPT_PARAMS" };

/**
 * Construct an {@link Error Error} with the `"ERR_CRYPTO_INVALID_STATE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CRYPTO_INVALID_STATE"` in builtins.d.ts.
 */
declare function $ERR_CRYPTO_INVALID_STATE(message: string): Error & { code: "ERR_CRYPTO_INVALID_STATE" };

/**
 * Construct an {@link RangeError RangeError} with the `"ERR_CRYPTO_INVALID_TAG_LENGTH"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CRYPTO_INVALID_TAG_LENGTH"` in builtins.d.ts.
 */
declare function $ERR_CRYPTO_INVALID_TAG_LENGTH(message: string): RangeError & { code: "ERR_CRYPTO_INVALID_TAG_LENGTH" };

/**
 * Construct an {@link Error Error} with the `"ERR_CRYPTO_JOB_INIT_FAILED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CRYPTO_JOB_INIT_FAILED"` in builtins.d.ts.
 */
declare function $ERR_CRYPTO_JOB_INIT_FAILED(message: string): Error & { code: "ERR_CRYPTO_JOB_INIT_FAILED" };

/**
 * Construct an {@link Error Error} with the `"ERR_CRYPTO_JWK_UNSUPPORTED_CURVE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CRYPTO_JWK_UNSUPPORTED_CURVE"` in builtins.d.ts.
 */
declare function $ERR_CRYPTO_JWK_UNSUPPORTED_CURVE(message: string): Error & { code: "ERR_CRYPTO_JWK_UNSUPPORTED_CURVE" };

/**
 * Construct an {@link Error Error} with the `"ERR_CRYPTO_JWK_UNSUPPORTED_KEY_TYPE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CRYPTO_JWK_UNSUPPORTED_KEY_TYPE"` in builtins.d.ts.
 */
declare function $ERR_CRYPTO_JWK_UNSUPPORTED_KEY_TYPE(message: string): Error & { code: "ERR_CRYPTO_JWK_UNSUPPORTED_KEY_TYPE" };

/**
 * Construct an {@link Error Error} with the `"ERR_CRYPTO_OPERATION_FAILED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CRYPTO_OPERATION_FAILED"` in builtins.d.ts.
 */
declare function $ERR_CRYPTO_OPERATION_FAILED(message: string): Error & { code: "ERR_CRYPTO_OPERATION_FAILED" };

/**
 * Construct an {@link Error Error} with the `"ERR_CRYPTO_SCRYPT_INVALID_PARAMETER"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CRYPTO_SCRYPT_INVALID_PARAMETER"` in builtins.d.ts.
 */
declare function $ERR_CRYPTO_SCRYPT_INVALID_PARAMETER(message: string): Error & { code: "ERR_CRYPTO_SCRYPT_INVALID_PARAMETER" };

/**
 * Construct an {@link Error Error} with the `"ERR_CRYPTO_SIGN_KEY_REQUIRED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CRYPTO_SIGN_KEY_REQUIRED"` in builtins.d.ts.
 */
declare function $ERR_CRYPTO_SIGN_KEY_REQUIRED(message: string): Error & { code: "ERR_CRYPTO_SIGN_KEY_REQUIRED" };

/**
 * Construct an {@link RangeError RangeError} with the `"ERR_CRYPTO_TIMING_SAFE_EQUAL_LENGTH"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CRYPTO_TIMING_SAFE_EQUAL_LENGTH"` in builtins.d.ts.
 */
declare function $ERR_CRYPTO_TIMING_SAFE_EQUAL_LENGTH(message: string): RangeError & { code: "ERR_CRYPTO_TIMING_SAFE_EQUAL_LENGTH" };

/**
 * Construct an {@link Error Error} with the `"ERR_CRYPTO_UNKNOWN_CIPHER"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CRYPTO_UNKNOWN_CIPHER"` in builtins.d.ts.
 */
declare function $ERR_CRYPTO_UNKNOWN_CIPHER(message: string): Error & { code: "ERR_CRYPTO_UNKNOWN_CIPHER" };

/**
 * Construct an {@link Error Error} with the `"ERR_CRYPTO_UNKNOWN_DH_GROUP"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CRYPTO_UNKNOWN_DH_GROUP"` in builtins.d.ts.
 */
declare function $ERR_CRYPTO_UNKNOWN_DH_GROUP(message: string): Error & { code: "ERR_CRYPTO_UNKNOWN_DH_GROUP" };

/**
 * Construct an {@link Error Error} with the `"ERR_CRYPTO_UNSUPPORTED_OPERATION"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_CRYPTO_UNSUPPORTED_OPERATION"` in builtins.d.ts.
 */
declare function $ERR_CRYPTO_UNSUPPORTED_OPERATION(message: string): Error & { code: "ERR_CRYPTO_UNSUPPORTED_OPERATION" };

/**
 * Construct an {@link Error Error} with the `"ERR_DLOPEN_DISABLED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_DLOPEN_DISABLED"` in builtins.d.ts.
 */
declare function $ERR_DLOPEN_DISABLED(message: string): Error & { code: "ERR_DLOPEN_DISABLED" };

/**
 * Construct an {@link Error Error} with the `"ERR_DLOPEN_FAILED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_DLOPEN_FAILED"` in builtins.d.ts.
 */
declare function $ERR_DLOPEN_FAILED(message: string): Error & { code: "ERR_DLOPEN_FAILED" };

/**
 * Construct an {@link Error Error} with the `"ERR_DNS_SET_SERVERS_FAILED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_DNS_SET_SERVERS_FAILED"` in builtins.d.ts.
 */
declare function $ERR_DNS_SET_SERVERS_FAILED(message: string): Error & { code: "ERR_DNS_SET_SERVERS_FAILED" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_ENCODING_INVALID_ENCODED_DATA"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_ENCODING_INVALID_ENCODED_DATA"` in builtins.d.ts.
 */
declare function $ERR_ENCODING_INVALID_ENCODED_DATA(message: string): TypeError & { code: "ERR_ENCODING_INVALID_ENCODED_DATA" };

/**
 * Construct an {@link RangeError RangeError} with the `"ERR_ENCODING_NOT_SUPPORTED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_ENCODING_NOT_SUPPORTED"` in builtins.d.ts.
 */
declare function $ERR_ENCODING_NOT_SUPPORTED(message: string): RangeError & { code: "ERR_ENCODING_NOT_SUPPORTED" };

/**
 * Construct an {@link Error Error} with the `"ERR_EVENT_RECURSION"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_EVENT_RECURSION"` in builtins.d.ts.
 */
declare function $ERR_EVENT_RECURSION(message: string): Error & { code: "ERR_EVENT_RECURSION" };

/**
 * Construct an {@link Error Error} with the `"ERR_EXECUTION_ENVIRONMENT_NOT_AVAILABLE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_EXECUTION_ENVIRONMENT_NOT_AVAILABLE"` in builtins.d.ts.
 */
declare function $ERR_EXECUTION_ENVIRONMENT_NOT_AVAILABLE(message: string): Error & { code: "ERR_EXECUTION_ENVIRONMENT_NOT_AVAILABLE" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_FORMDATA_PARSE_ERROR"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_FORMDATA_PARSE_ERROR"` in builtins.d.ts.
 */
declare function $ERR_FORMDATA_PARSE_ERROR(message: string): TypeError & { code: "ERR_FORMDATA_PARSE_ERROR" };

/**
 * Construct an {@link Error Error} with the `"ERR_FS_CP_DIR_TO_NON_DIR"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_FS_CP_DIR_TO_NON_DIR"` in builtins.d.ts.
 */
declare function $ERR_FS_CP_DIR_TO_NON_DIR(message: string): Error & { code: "ERR_FS_CP_DIR_TO_NON_DIR" };

/**
 * Construct an {@link Error Error} with the `"ERR_FS_CP_EINVAL"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_FS_CP_EINVAL"` in builtins.d.ts.
 */
declare function $ERR_FS_CP_EINVAL(message: string): Error & { code: "ERR_FS_CP_EINVAL" };

/**
 * Construct an {@link Error Error} with the `"ERR_FS_CP_FIFO_PIPE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_FS_CP_FIFO_PIPE"` in builtins.d.ts.
 */
declare function $ERR_FS_CP_FIFO_PIPE(message: string): Error & { code: "ERR_FS_CP_FIFO_PIPE" };

/**
 * Construct an {@link Error Error} with the `"ERR_FS_CP_NON_DIR_TO_DIR"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_FS_CP_NON_DIR_TO_DIR"` in builtins.d.ts.
 */
declare function $ERR_FS_CP_NON_DIR_TO_DIR(message: string): Error & { code: "ERR_FS_CP_NON_DIR_TO_DIR" };

/**
 * Construct an {@link Error Error} with the `"ERR_FS_CP_SOCKET"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_FS_CP_SOCKET"` in builtins.d.ts.
 */
declare function $ERR_FS_CP_SOCKET(message: string): Error & { code: "ERR_FS_CP_SOCKET" };

/**
 * Construct an {@link Error Error} with the `"ERR_FS_CP_UNKNOWN"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_FS_CP_UNKNOWN"` in builtins.d.ts.
 */
declare function $ERR_FS_CP_UNKNOWN(message: string): Error & { code: "ERR_FS_CP_UNKNOWN" };

/**
 * Construct an {@link Error Error} with the `"ERR_FS_EISDIR"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_FS_EISDIR"` in builtins.d.ts.
 */
declare function $ERR_FS_EISDIR(message: string): Error & { code: "ERR_FS_EISDIR" };

/**
 * Construct an {@link Error Error} with the `"ERR_HTTP_CONTENT_LENGTH_MISMATCH"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_HTTP_CONTENT_LENGTH_MISMATCH"` in builtins.d.ts.
 */
declare function $ERR_HTTP_CONTENT_LENGTH_MISMATCH(message: string): Error & { code: "ERR_HTTP_CONTENT_LENGTH_MISMATCH" };

/**
 * Construct an {@link Error Error} with the `"ERR_HTTP_TRAILER_INVALID"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_HTTP_TRAILER_INVALID"` in builtins.d.ts.
 */
declare function $ERR_HTTP_TRAILER_INVALID(message: string): Error & { code: "ERR_HTTP_TRAILER_INVALID" };

/**
 * Construct an {@link Error Error} with the `"ERR_HTTP2_ERROR"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_HTTP2_ERROR"` in builtins.d.ts.
 */
declare function $ERR_HTTP2_ERROR(message: string): Error & { code: "ERR_HTTP2_ERROR" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_HTTP2_HEADER_SINGLE_VALUE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_HTTP2_HEADER_SINGLE_VALUE"` in builtins.d.ts.
 */
declare function $ERR_HTTP2_HEADER_SINGLE_VALUE(message: string): TypeError & { code: "ERR_HTTP2_HEADER_SINGLE_VALUE" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_HTTP2_ORIGIN_LENGTH"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_HTTP2_ORIGIN_LENGTH"` in builtins.d.ts.
 */
declare function $ERR_HTTP2_ORIGIN_LENGTH(message: string): TypeError & { code: "ERR_HTTP2_ORIGIN_LENGTH" };

/**
 * Construct an {@link Error Error} with the `"ERR_HTTP2_UNSUPPORTED_PROTOCOL"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_HTTP2_UNSUPPORTED_PROTOCOL"` in builtins.d.ts.
 */
declare function $ERR_HTTP2_UNSUPPORTED_PROTOCOL(message: string): Error & { code: "ERR_HTTP2_UNSUPPORTED_PROTOCOL" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_HTTP2_INVALID_SETTING_VALUE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_HTTP2_INVALID_SETTING_VALUE"` in builtins.d.ts.
 */
declare function $ERR_HTTP2_INVALID_SETTING_VALUE(message: string): TypeError & { code: "ERR_HTTP2_INVALID_SETTING_VALUE" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_INCOMPATIBLE_OPTION_PAIR"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_INCOMPATIBLE_OPTION_PAIR"` in builtins.d.ts.
 */
declare function $ERR_INCOMPATIBLE_OPTION_PAIR(message: string): TypeError & { code: "ERR_INCOMPATIBLE_OPTION_PAIR" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_INVALID_FILE_URL_HOST"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_INVALID_FILE_URL_HOST"` in builtins.d.ts.
 */
declare function $ERR_INVALID_FILE_URL_HOST(message: string): TypeError & { code: "ERR_INVALID_FILE_URL_HOST" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_INVALID_FILE_URL_PATH"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_INVALID_FILE_URL_PATH"` in builtins.d.ts.
 */
declare function $ERR_INVALID_FILE_URL_PATH(message: string): TypeError & { code: "ERR_INVALID_FILE_URL_PATH" };

/**
 * Construct an {@link Error Error} with the `"ERR_INVALID_MODULE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_INVALID_MODULE"` in builtins.d.ts.
 */
declare function $ERR_INVALID_MODULE(message: string): Error & { code: "ERR_INVALID_MODULE" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_INVALID_OBJECT_DEFINE_PROPERTY"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_INVALID_OBJECT_DEFINE_PROPERTY"` in builtins.d.ts.
 */
declare function $ERR_INVALID_OBJECT_DEFINE_PROPERTY(message: string): TypeError & { code: "ERR_INVALID_OBJECT_DEFINE_PROPERTY" };

/**
 * Construct an {@link Error Error} with the `"ERR_INVALID_PACKAGE_CONFIG"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_INVALID_PACKAGE_CONFIG"` in builtins.d.ts.
 */
declare function $ERR_INVALID_PACKAGE_CONFIG(message: string): Error & { code: "ERR_INVALID_PACKAGE_CONFIG" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_INVALID_THIS"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_INVALID_THIS"` in builtins.d.ts.
 */
declare function $ERR_INVALID_THIS(message: string): TypeError & { code: "ERR_INVALID_THIS" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_INVALID_URL_SCHEME"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_INVALID_URL_SCHEME"` in builtins.d.ts.
 */
declare function $ERR_INVALID_URL_SCHEME(message: string): TypeError & { code: "ERR_INVALID_URL_SCHEME" };

/**
 * Construct an {@link Error Error} with the `"ERR_LOAD_SQLITE_EXTENSION"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_LOAD_SQLITE_EXTENSION"` in builtins.d.ts.
 */
declare function $ERR_LOAD_SQLITE_EXTENSION(message: string): Error & { code: "ERR_LOAD_SQLITE_EXTENSION" };

/**
 * Construct an {@link Error Error} with the `"ERR_MEMORY_ALLOCATION_FAILED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_MEMORY_ALLOCATION_FAILED"` in builtins.d.ts.
 */
declare function $ERR_MEMORY_ALLOCATION_FAILED(message: string): Error & { code: "ERR_MEMORY_ALLOCATION_FAILED" };

/**
 * Construct an {@link Error Error} with the `"ERR_MESSAGE_TARGET_CONTEXT_UNAVAILABLE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_MESSAGE_TARGET_CONTEXT_UNAVAILABLE"` in builtins.d.ts.
 */
declare function $ERR_MESSAGE_TARGET_CONTEXT_UNAVAILABLE(message: string): Error & { code: "ERR_MESSAGE_TARGET_CONTEXT_UNAVAILABLE" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_MISSING_PASSPHRASE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_MISSING_PASSPHRASE"` in builtins.d.ts.
 */
declare function $ERR_MISSING_PASSPHRASE(message: string): TypeError & { code: "ERR_MISSING_PASSPHRASE" };

/**
 * Construct an {@link Error Error} with the `"ERR_MISSING_PLATFORM_FOR_WORKER"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_MISSING_PLATFORM_FOR_WORKER"` in builtins.d.ts.
 */
declare function $ERR_MISSING_PLATFORM_FOR_WORKER(message: string): Error & { code: "ERR_MISSING_PLATFORM_FOR_WORKER" };

/**
 * Construct an {@link Error Error} with the `"ERR_MODULE_NOT_FOUND"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_MODULE_NOT_FOUND"` in builtins.d.ts.
 */
declare function $ERR_MODULE_NOT_FOUND(message: string): Error & { code: "ERR_MODULE_NOT_FOUND" };

/**
 * Construct an {@link Error Error} with the `"ERR_NON_CONTEXT_AWARE_DISABLED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_NON_CONTEXT_AWARE_DISABLED"` in builtins.d.ts.
 */
declare function $ERR_NON_CONTEXT_AWARE_DISABLED(message: string): Error & { code: "ERR_NON_CONTEXT_AWARE_DISABLED" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_PARSE_ARGS_INVALID_OPTION_VALUE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_PARSE_ARGS_INVALID_OPTION_VALUE"` in builtins.d.ts.
 */
declare function $ERR_PARSE_ARGS_INVALID_OPTION_VALUE(message: string): TypeError & { code: "ERR_PARSE_ARGS_INVALID_OPTION_VALUE" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_PARSE_ARGS_UNEXPECTED_POSITIONAL"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_PARSE_ARGS_UNEXPECTED_POSITIONAL"` in builtins.d.ts.
 */
declare function $ERR_PARSE_ARGS_UNEXPECTED_POSITIONAL(message: string): TypeError & { code: "ERR_PARSE_ARGS_UNEXPECTED_POSITIONAL" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_PARSE_ARGS_UNKNOWN_OPTION"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_PARSE_ARGS_UNKNOWN_OPTION"` in builtins.d.ts.
 */
declare function $ERR_PARSE_ARGS_UNKNOWN_OPTION(message: string): TypeError & { code: "ERR_PARSE_ARGS_UNKNOWN_OPTION" };

/**
 * Construct an {@link Error Error} with the `"ERR_POSTGRES_AUTHENTICATION_FAILED_PBKDF2"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_AUTHENTICATION_FAILED_PBKDF2"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_AUTHENTICATION_FAILED_PBKDF2(message: string): Error & { name: "PostgresError", code: "ERR_POSTGRES_AUTHENTICATION_FAILED_PBKDF2" };

/**
 * Construct an {@link Error Error} with the `"ERR_POSTGRES_CONNECTION_CLOSED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_CONNECTION_CLOSED"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_CONNECTION_CLOSED(message: string): Error & { name: "PostgresError", code: "ERR_POSTGRES_CONNECTION_CLOSED" };

/**
 * Construct an {@link Error Error} with the `"ERR_POSTGRES_CONNECTION_TIMEOUT"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_CONNECTION_TIMEOUT"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_CONNECTION_TIMEOUT(message: string): Error & { name: "PostgresError", code: "ERR_POSTGRES_CONNECTION_TIMEOUT" };

/**
 * Construct an {@link Error Error} with the `"ERR_POSTGRES_EXPECTED_REQUEST"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_EXPECTED_REQUEST"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_EXPECTED_REQUEST(message: string): Error & { name: "PostgresError", code: "ERR_POSTGRES_EXPECTED_REQUEST" };

/**
 * Construct an {@link Error Error} with the `"ERR_POSTGRES_EXPECTED_STATEMENT"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_EXPECTED_STATEMENT"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_EXPECTED_STATEMENT(message: string): Error & { name: "PostgresError", code: "ERR_POSTGRES_EXPECTED_STATEMENT" };

/**
 * Construct an {@link Error Error} with the `"ERR_POSTGRES_IDLE_TIMEOUT"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_IDLE_TIMEOUT"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_IDLE_TIMEOUT(message: string): Error & { name: "PostgresError", code: "ERR_POSTGRES_IDLE_TIMEOUT" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_POSTGRES_INVALID_BACKEND_KEY_DATA"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_INVALID_BACKEND_KEY_DATA"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_INVALID_BACKEND_KEY_DATA(message: string): TypeError & { name: "PostgresError", code: "ERR_POSTGRES_INVALID_BACKEND_KEY_DATA" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_POSTGRES_INVALID_BINARY_DATA"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_INVALID_BINARY_DATA"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_INVALID_BINARY_DATA(message: string): TypeError & { name: "PostgresError", code: "ERR_POSTGRES_INVALID_BINARY_DATA" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_POSTGRES_INVALID_BYTE_SEQUENCE_FOR_ENCODING"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_INVALID_BYTE_SEQUENCE_FOR_ENCODING"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_INVALID_BYTE_SEQUENCE_FOR_ENCODING(message: string): TypeError & { name: "PostgresError", code: "ERR_POSTGRES_INVALID_BYTE_SEQUENCE_FOR_ENCODING" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_POSTGRES_INVALID_BYTE_SEQUENCE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_INVALID_BYTE_SEQUENCE"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_INVALID_BYTE_SEQUENCE(message: string): TypeError & { name: "PostgresError", code: "ERR_POSTGRES_INVALID_BYTE_SEQUENCE" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_POSTGRES_INVALID_CHARACTER"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_INVALID_CHARACTER"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_INVALID_CHARACTER(message: string): TypeError & { name: "PostgresError", code: "ERR_POSTGRES_INVALID_CHARACTER" };

/**
 * Construct an {@link Error Error} with the `"ERR_POSTGRES_INVALID_MESSAGE_LENGTH"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_INVALID_MESSAGE_LENGTH"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_INVALID_MESSAGE_LENGTH(message: string): Error & { name: "PostgresError", code: "ERR_POSTGRES_INVALID_MESSAGE_LENGTH" };

/**
 * Construct an {@link Error Error} with the `"ERR_POSTGRES_INVALID_MESSAGE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_INVALID_MESSAGE"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_INVALID_MESSAGE(message: string): Error & { name: "PostgresError", code: "ERR_POSTGRES_INVALID_MESSAGE" };

/**
 * Construct an {@link Error Error} with the `"ERR_POSTGRES_INVALID_QUERY_BINDING"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_INVALID_QUERY_BINDING"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_INVALID_QUERY_BINDING(message: string): Error & { name: "PostgresError", code: "ERR_POSTGRES_INVALID_QUERY_BINDING" };

/**
 * Construct an {@link Error Error} with the `"ERR_POSTGRES_INVALID_SERVER_KEY"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_INVALID_SERVER_KEY"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_INVALID_SERVER_KEY(message: string): Error & { name: "PostgresError", code: "ERR_POSTGRES_INVALID_SERVER_KEY" };

/**
 * Construct an {@link Error Error} with the `"ERR_POSTGRES_INVALID_SERVER_SIGNATURE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_INVALID_SERVER_SIGNATURE"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_INVALID_SERVER_SIGNATURE(message: string): Error & { name: "PostgresError", code: "ERR_POSTGRES_INVALID_SERVER_SIGNATURE" };

/**
 * Construct an {@link Error Error} with the `"ERR_POSTGRES_INVALID_TRANSACTION_STATE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_INVALID_TRANSACTION_STATE"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_INVALID_TRANSACTION_STATE(message: string): Error & { name: "PostgresError", code: "ERR_POSTGRES_INVALID_TRANSACTION_STATE" };

/**
 * Construct an {@link Error Error} with the `"ERR_POSTGRES_LIFETIME_TIMEOUT"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_LIFETIME_TIMEOUT"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_LIFETIME_TIMEOUT(message: string): Error & { name: "PostgresError", code: "ERR_POSTGRES_LIFETIME_TIMEOUT" };

/**
 * Construct an {@link Error Error} with the `"ERR_POSTGRES_MULTIDIMENSIONAL_ARRAY_NOT_SUPPORTED_YET"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_MULTIDIMENSIONAL_ARRAY_NOT_SUPPORTED_YET"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_MULTIDIMENSIONAL_ARRAY_NOT_SUPPORTED_YET(message: string): Error & { name: "PostgresError", code: "ERR_POSTGRES_MULTIDIMENSIONAL_ARRAY_NOT_SUPPORTED_YET" };

/**
 * Construct an {@link Error Error} with the `"ERR_POSTGRES_NOT_TAGGED_CALL"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_NOT_TAGGED_CALL"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_NOT_TAGGED_CALL(message: string): Error & { name: "PostgresError", code: "ERR_POSTGRES_NOT_TAGGED_CALL" };

/**
 * Construct an {@link Error Error} with the `"ERR_POSTGRES_NULLS_IN_ARRAY_NOT_SUPPORTED_YET"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_NULLS_IN_ARRAY_NOT_SUPPORTED_YET"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_NULLS_IN_ARRAY_NOT_SUPPORTED_YET(message: string): Error & { name: "PostgresError", code: "ERR_POSTGRES_NULLS_IN_ARRAY_NOT_SUPPORTED_YET" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_POSTGRES_OVERFLOW"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_OVERFLOW"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_OVERFLOW(message: string): TypeError & { name: "PostgresError", code: "ERR_POSTGRES_OVERFLOW" };

/**
 * Construct an {@link Error Error} with the `"ERR_POSTGRES_QUERY_CANCELLED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_QUERY_CANCELLED"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_QUERY_CANCELLED(message: string): Error & { name: "PostgresError", code: "ERR_POSTGRES_QUERY_CANCELLED" };

/**
 * Construct an {@link Error Error} with the `"ERR_POSTGRES_SASL_SIGNATURE_INVALID_BASE64"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_SASL_SIGNATURE_INVALID_BASE64"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_SASL_SIGNATURE_INVALID_BASE64(message: string): Error & { name: "PostgresError", code: "ERR_POSTGRES_SASL_SIGNATURE_INVALID_BASE64" };

/**
 * Construct an {@link Error Error} with the `"ERR_POSTGRES_SASL_SIGNATURE_MISMATCH"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_SASL_SIGNATURE_MISMATCH"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_SASL_SIGNATURE_MISMATCH(message: string): Error & { name: "PostgresError", code: "ERR_POSTGRES_SASL_SIGNATURE_MISMATCH" };

/**
 * Construct an {@link Error Error} with the `"ERR_POSTGRES_SERVER_ERROR"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_SERVER_ERROR"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_SERVER_ERROR(message: string): Error & { name: "PostgresError", code: "ERR_POSTGRES_SERVER_ERROR" };

/**
 * Construct an {@link SyntaxError SyntaxError} with the `"ERR_POSTGRES_SYNTAX_ERROR"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_SYNTAX_ERROR"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_SYNTAX_ERROR(message: string): SyntaxError & { name: "PostgresError", code: "ERR_POSTGRES_SYNTAX_ERROR" };

/**
 * Construct an {@link Error Error} with the `"ERR_POSTGRES_TLS_NOT_AVAILABLE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_TLS_NOT_AVAILABLE"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_TLS_NOT_AVAILABLE(message: string): Error & { name: "PostgresError", code: "ERR_POSTGRES_TLS_NOT_AVAILABLE" };

/**
 * Construct an {@link Error Error} with the `"ERR_POSTGRES_TLS_UPGRADE_FAILED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_TLS_UPGRADE_FAILED"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_TLS_UPGRADE_FAILED(message: string): Error & { name: "PostgresError", code: "ERR_POSTGRES_TLS_UPGRADE_FAILED" };

/**
 * Construct an {@link Error Error} with the `"ERR_POSTGRES_UNEXPECTED_MESSAGE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_UNEXPECTED_MESSAGE"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_UNEXPECTED_MESSAGE(message: string): Error & { name: "PostgresError", code: "ERR_POSTGRES_UNEXPECTED_MESSAGE" };

/**
 * Construct an {@link Error Error} with the `"ERR_POSTGRES_UNKNOWN_AUTHENTICATION_METHOD"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_UNKNOWN_AUTHENTICATION_METHOD"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_UNKNOWN_AUTHENTICATION_METHOD(message: string): Error & { name: "PostgresError", code: "ERR_POSTGRES_UNKNOWN_AUTHENTICATION_METHOD" };

/**
 * Construct an {@link Error Error} with the `"ERR_POSTGRES_UNKNOWN_FORMAT_CODE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_UNKNOWN_FORMAT_CODE"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_UNKNOWN_FORMAT_CODE(message: string): Error & { name: "PostgresError", code: "ERR_POSTGRES_UNKNOWN_FORMAT_CODE" };

/**
 * Construct an {@link Error Error} with the `"ERR_POSTGRES_UNSAFE_TRANSACTION"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_UNSAFE_TRANSACTION"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_UNSAFE_TRANSACTION(message: string): Error & { name: "PostgresError", code: "ERR_POSTGRES_UNSAFE_TRANSACTION" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_POSTGRES_UNSUPPORTED_ARRAY_FORMAT"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_UNSUPPORTED_ARRAY_FORMAT"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_UNSUPPORTED_ARRAY_FORMAT(message: string): TypeError & { name: "PostgresError", code: "ERR_POSTGRES_UNSUPPORTED_ARRAY_FORMAT" };

/**
 * Construct an {@link Error Error} with the `"ERR_POSTGRES_UNSUPPORTED_AUTHENTICATION_METHOD"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_UNSUPPORTED_AUTHENTICATION_METHOD"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_UNSUPPORTED_AUTHENTICATION_METHOD(message: string): Error & { name: "PostgresError", code: "ERR_POSTGRES_UNSUPPORTED_AUTHENTICATION_METHOD" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_POSTGRES_UNSUPPORTED_BYTEA_FORMAT"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_UNSUPPORTED_BYTEA_FORMAT"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_UNSUPPORTED_BYTEA_FORMAT(message: string): TypeError & { name: "PostgresError", code: "ERR_POSTGRES_UNSUPPORTED_BYTEA_FORMAT" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_POSTGRES_UNSUPPORTED_INTEGER_SIZE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_UNSUPPORTED_INTEGER_SIZE"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_UNSUPPORTED_INTEGER_SIZE(message: string): TypeError & { name: "PostgresError", code: "ERR_POSTGRES_UNSUPPORTED_INTEGER_SIZE" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_POSTGRES_UNSUPPORTED_NUMERIC_FORMAT"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_POSTGRES_UNSUPPORTED_NUMERIC_FORMAT"` in builtins.d.ts.
 */
declare function $ERR_POSTGRES_UNSUPPORTED_NUMERIC_FORMAT(message: string): TypeError & { name: "PostgresError", code: "ERR_POSTGRES_UNSUPPORTED_NUMERIC_FORMAT" };

/**
 * Construct an {@link Error Error} with the `"ERR_PROXY_INVALID_CONFIG"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_PROXY_INVALID_CONFIG"` in builtins.d.ts.
 */
declare function $ERR_PROXY_INVALID_CONFIG(message: string): Error & { code: "ERR_PROXY_INVALID_CONFIG" };

/**
 * Construct an {@link Error Error} with the `"ERR_MYSQL_CONNECTION_CLOSED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_MYSQL_CONNECTION_CLOSED"` in builtins.d.ts.
 */
declare function $ERR_MYSQL_CONNECTION_CLOSED(message: string): Error & { name: "MySQLError", code: "ERR_MYSQL_CONNECTION_CLOSED" };

/**
 * Construct an {@link Error Error} with the `"ERR_MYSQL_CONNECTION_TIMEOUT"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_MYSQL_CONNECTION_TIMEOUT"` in builtins.d.ts.
 */
declare function $ERR_MYSQL_CONNECTION_TIMEOUT(message: string): Error & { name: "MySQLError", code: "ERR_MYSQL_CONNECTION_TIMEOUT" };

/**
 * Construct an {@link Error Error} with the `"ERR_MYSQL_IDLE_TIMEOUT"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_MYSQL_IDLE_TIMEOUT"` in builtins.d.ts.
 */
declare function $ERR_MYSQL_IDLE_TIMEOUT(message: string): Error & { name: "MySQLError", code: "ERR_MYSQL_IDLE_TIMEOUT" };

/**
 * Construct an {@link Error Error} with the `"ERR_MYSQL_LIFETIME_TIMEOUT"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_MYSQL_LIFETIME_TIMEOUT"` in builtins.d.ts.
 */
declare function $ERR_MYSQL_LIFETIME_TIMEOUT(message: string): Error & { name: "MySQLError", code: "ERR_MYSQL_LIFETIME_TIMEOUT" };

/**
 * Construct an {@link Error Error} with the `"ERR_UNHANDLED_REJECTION"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_UNHANDLED_REJECTION"` in builtins.d.ts.
 */
declare function $ERR_UNHANDLED_REJECTION(message: string): Error & { name: "UnhandledPromiseRejection", code: "ERR_UNHANDLED_REJECTION" };

/**
 * Construct an {@link Error Error} with the `"ERR_REQUIRE_ASYNC_MODULE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_REQUIRE_ASYNC_MODULE"` in builtins.d.ts.
 */
declare function $ERR_REQUIRE_ASYNC_MODULE(message: string): Error & { code: "ERR_REQUIRE_ASYNC_MODULE" };

/**
 * Construct an {@link Error Error} with the `"ERR_S3_INVALID_ENDPOINT"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_S3_INVALID_ENDPOINT"` in builtins.d.ts.
 */
declare function $ERR_S3_INVALID_ENDPOINT(message: string): Error & { code: "ERR_S3_INVALID_ENDPOINT" };

/**
 * Construct an {@link Error Error} with the `"ERR_S3_INVALID_METHOD"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_S3_INVALID_METHOD"` in builtins.d.ts.
 */
declare function $ERR_S3_INVALID_METHOD(message: string): Error & { code: "ERR_S3_INVALID_METHOD" };

/**
 * Construct an {@link Error Error} with the `"ERR_S3_INVALID_PATH"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_S3_INVALID_PATH"` in builtins.d.ts.
 */
declare function $ERR_S3_INVALID_PATH(message: string): Error & { code: "ERR_S3_INVALID_PATH" };

/**
 * Construct an {@link Error Error} with the `"ERR_S3_INVALID_SESSION_TOKEN"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_S3_INVALID_SESSION_TOKEN"` in builtins.d.ts.
 */
declare function $ERR_S3_INVALID_SESSION_TOKEN(message: string): Error & { code: "ERR_S3_INVALID_SESSION_TOKEN" };

/**
 * Construct an {@link Error Error} with the `"ERR_S3_INVALID_SIGNATURE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_S3_INVALID_SIGNATURE"` in builtins.d.ts.
 */
declare function $ERR_S3_INVALID_SIGNATURE(message: string): Error & { code: "ERR_S3_INVALID_SIGNATURE" };

/**
 * Construct an {@link Error Error} with the `"ERR_S3_MISSING_CREDENTIALS"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_S3_MISSING_CREDENTIALS"` in builtins.d.ts.
 */
declare function $ERR_S3_MISSING_CREDENTIALS(message: string): Error & { code: "ERR_S3_MISSING_CREDENTIALS" };

/**
 * Construct an {@link Error Error} with the `"ERR_SCRIPT_EXECUTION_INTERRUPTED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_SCRIPT_EXECUTION_INTERRUPTED"` in builtins.d.ts.
 */
declare function $ERR_SCRIPT_EXECUTION_INTERRUPTED(message: string): Error & { code: "ERR_SCRIPT_EXECUTION_INTERRUPTED" };

/**
 * Construct an {@link Error Error} with the `"ERR_SCRIPT_EXECUTION_TIMEOUT"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_SCRIPT_EXECUTION_TIMEOUT"` in builtins.d.ts.
 */
declare function $ERR_SCRIPT_EXECUTION_TIMEOUT(message: string): Error & { code: "ERR_SCRIPT_EXECUTION_TIMEOUT" };

/**
 * Construct an {@link RangeError RangeError} with the `"ERR_SOCKET_BAD_PORT"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_SOCKET_BAD_PORT"` in builtins.d.ts.
 */
declare function $ERR_SOCKET_BAD_PORT(message: string): RangeError & { code: "ERR_SOCKET_BAD_PORT" };

/**
 * Construct an {@link Error Error} with the `"ERR_SSR_RESPONSE_EXPECTED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_SSR_RESPONSE_EXPECTED"` in builtins.d.ts.
 */
declare function $ERR_SSR_RESPONSE_EXPECTED(message: string): Error & { code: "ERR_SSR_RESPONSE_EXPECTED" };

/**
 * Construct an {@link Error Error} with the `"ERR_STREAM_RELEASE_LOCK"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_STREAM_RELEASE_LOCK"` in builtins.d.ts.
 */
declare function $ERR_STREAM_RELEASE_LOCK(message: string): Error & { name: "AbortError", code: "ERR_STREAM_RELEASE_LOCK" };

/**
 * Construct an {@link Error Error} with the `"ERR_STREAM_WRAP"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_STREAM_WRAP"` in builtins.d.ts.
 */
declare function $ERR_STREAM_WRAP(message: string): Error & { code: "ERR_STREAM_WRAP" };

/**
 * Construct an {@link Error Error} with the `"ERR_STRING_TOO_LONG"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_STRING_TOO_LONG"` in builtins.d.ts.
 */
declare function $ERR_STRING_TOO_LONG(message: string): Error & { code: "ERR_STRING_TOO_LONG" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_TLS_INVALID_PROTOCOL_METHOD"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_TLS_INVALID_PROTOCOL_METHOD"` in builtins.d.ts.
 */
declare function $ERR_TLS_INVALID_PROTOCOL_METHOD(message: string): TypeError & { code: "ERR_TLS_INVALID_PROTOCOL_METHOD" };

/**
 * Construct an {@link Error Error} with the `"ERR_TLS_PSK_SET_IDENTITY_HINT_FAILED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_TLS_PSK_SET_IDENTITY_HINT_FAILED"` in builtins.d.ts.
 */
declare function $ERR_TLS_PSK_SET_IDENTITY_HINT_FAILED(message: string): Error & { code: "ERR_TLS_PSK_SET_IDENTITY_HINT_FAILED" };

/**
 * Construct an {@link Error Error} with the `"ERR_UNCAUGHT_EXCEPTION_CAPTURE_ALREADY_SET"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_UNCAUGHT_EXCEPTION_CAPTURE_ALREADY_SET"` in builtins.d.ts.
 */
declare function $ERR_UNCAUGHT_EXCEPTION_CAPTURE_ALREADY_SET(message: string): Error & { code: "ERR_UNCAUGHT_EXCEPTION_CAPTURE_ALREADY_SET" };

/**
 * Construct an {@link Error Error} with the `"ERR_UNKNOWN_CREDENTIAL"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_UNKNOWN_CREDENTIAL"` in builtins.d.ts.
 */
declare function $ERR_UNKNOWN_CREDENTIAL(message: string): Error & { code: "ERR_UNKNOWN_CREDENTIAL" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_UNKNOWN_SIGNAL"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_UNKNOWN_SIGNAL"` in builtins.d.ts.
 */
declare function $ERR_UNKNOWN_SIGNAL(message: string): TypeError & { code: "ERR_UNKNOWN_SIGNAL" };

/**
 * Construct an {@link RangeError RangeError} with the `"ERR_ZSTD_INVALID_PARAM"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_ZSTD_INVALID_PARAM"` in builtins.d.ts.
 */
declare function $ERR_ZSTD_INVALID_PARAM(message: string): RangeError & { code: "ERR_ZSTD_INVALID_PARAM" };

/**
 * Construct an {@link Error Error} with the `"ERR_WASI_NOT_STARTED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_WASI_NOT_STARTED"` in builtins.d.ts.
 */
declare function $ERR_WASI_NOT_STARTED(message: string): Error & { code: "ERR_WASI_NOT_STARTED" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_WEBASSEMBLY_RESPONSE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_WEBASSEMBLY_RESPONSE"` in builtins.d.ts.
 */
declare function $ERR_WEBASSEMBLY_RESPONSE(message: string): TypeError & { code: "ERR_WEBASSEMBLY_RESPONSE" };

/**
 * Construct an {@link Error Error} with the `"ERR_WORKER_INIT_FAILED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_WORKER_INIT_FAILED"` in builtins.d.ts.
 */
declare function $ERR_WORKER_INIT_FAILED(message: string): Error & { code: "ERR_WORKER_INIT_FAILED" };

/**
 * Construct an {@link Error Error} with the `"ERR_WORKER_NOT_RUNNING"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_WORKER_NOT_RUNNING"` in builtins.d.ts.
 */
declare function $ERR_WORKER_NOT_RUNNING(message: string): Error & { code: "ERR_WORKER_NOT_RUNNING" };

/**
 * Construct an {@link Error Error} with the `"MODULE_NOT_FOUND"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"MODULE_NOT_FOUND"` in builtins.d.ts.
 */
declare function $MODULE_NOT_FOUND(message: string): Error & { code: "MODULE_NOT_FOUND" };

/**
 * Construct an {@link Error Error} with the `"ERR_INTERNAL_ASSERTION"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_INTERNAL_ASSERTION"` in builtins.d.ts.
 */
declare function $ERR_INTERNAL_ASSERTION(message: string): Error & { code: "ERR_INTERNAL_ASSERTION" };

/**
 * Construct an {@link Error Error} with the `"ERR_OSSL_EVP_INVALID_DIGEST"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_OSSL_EVP_INVALID_DIGEST"` in builtins.d.ts.
 */
declare function $ERR_OSSL_EVP_INVALID_DIGEST(message: string): Error & { code: "ERR_OSSL_EVP_INVALID_DIGEST" };

/**
 * Construct an {@link Error Error} with the `"ERR_KEY_GENERATION_JOB_FAILED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_KEY_GENERATION_JOB_FAILED"` in builtins.d.ts.
 */
declare function $ERR_KEY_GENERATION_JOB_FAILED(message: string): Error & { code: "ERR_KEY_GENERATION_JOB_FAILED" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_MISSING_OPTION"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_MISSING_OPTION"` in builtins.d.ts.
 */
declare function $ERR_MISSING_OPTION(message: string): TypeError & { code: "ERR_MISSING_OPTION" };

/**
 * Construct an {@link Error Error} with the `"ERR_REDIS_AUTHENTICATION_FAILED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_REDIS_AUTHENTICATION_FAILED"` in builtins.d.ts.
 */
declare function $ERR_REDIS_AUTHENTICATION_FAILED(message: string): Error & { name: "RedisError", code: "ERR_REDIS_AUTHENTICATION_FAILED" };

/**
 * Construct an {@link Error Error} with the `"ERR_REDIS_CONNECTION_CLOSED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_REDIS_CONNECTION_CLOSED"` in builtins.d.ts.
 */
declare function $ERR_REDIS_CONNECTION_CLOSED(message: string): Error & { name: "RedisError", code: "ERR_REDIS_CONNECTION_CLOSED" };

/**
 * Construct an {@link Error Error} with the `"ERR_REDIS_CONNECTION_TIMEOUT"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_REDIS_CONNECTION_TIMEOUT"` in builtins.d.ts.
 */
declare function $ERR_REDIS_CONNECTION_TIMEOUT(message: string): Error & { name: "RedisError", code: "ERR_REDIS_CONNECTION_TIMEOUT" };

/**
 * Construct an {@link Error Error} with the `"ERR_REDIS_IDLE_TIMEOUT"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_REDIS_IDLE_TIMEOUT"` in builtins.d.ts.
 */
declare function $ERR_REDIS_IDLE_TIMEOUT(message: string): Error & { name: "RedisError", code: "ERR_REDIS_IDLE_TIMEOUT" };

/**
 * Construct an {@link Error Error} with the `"ERR_REDIS_INVALID_ARGUMENT"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_REDIS_INVALID_ARGUMENT"` in builtins.d.ts.
 */
declare function $ERR_REDIS_INVALID_ARGUMENT(message: string): Error & { name: "RedisError", code: "ERR_REDIS_INVALID_ARGUMENT" };

/**
 * Construct an {@link Error Error} with the `"ERR_REDIS_INVALID_ARRAY"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_REDIS_INVALID_ARRAY"` in builtins.d.ts.
 */
declare function $ERR_REDIS_INVALID_ARRAY(message: string): Error & { name: "RedisError", code: "ERR_REDIS_INVALID_ARRAY" };

/**
 * Construct an {@link Error Error} with the `"ERR_REDIS_INVALID_BULK_STRING"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_REDIS_INVALID_BULK_STRING"` in builtins.d.ts.
 */
declare function $ERR_REDIS_INVALID_BULK_STRING(message: string): Error & { name: "RedisError", code: "ERR_REDIS_INVALID_BULK_STRING" };

/**
 * Construct an {@link Error Error} with the `"ERR_REDIS_INVALID_COMMAND"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_REDIS_INVALID_COMMAND"` in builtins.d.ts.
 */
declare function $ERR_REDIS_INVALID_COMMAND(message: string): Error & { name: "RedisError", code: "ERR_REDIS_INVALID_COMMAND" };

/**
 * Construct an {@link Error Error} with the `"ERR_REDIS_INVALID_DATABASE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_REDIS_INVALID_DATABASE"` in builtins.d.ts.
 */
declare function $ERR_REDIS_INVALID_DATABASE(message: string): Error & { name: "RedisError", code: "ERR_REDIS_INVALID_DATABASE" };

/**
 * Construct an {@link Error Error} with the `"ERR_REDIS_INVALID_ERROR_STRING"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_REDIS_INVALID_ERROR_STRING"` in builtins.d.ts.
 */
declare function $ERR_REDIS_INVALID_ERROR_STRING(message: string): Error & { name: "RedisError", code: "ERR_REDIS_INVALID_ERROR_STRING" };

/**
 * Construct an {@link Error Error} with the `"ERR_REDIS_INVALID_INTEGER"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_REDIS_INVALID_INTEGER"` in builtins.d.ts.
 */
declare function $ERR_REDIS_INVALID_INTEGER(message: string): Error & { name: "RedisError", code: "ERR_REDIS_INVALID_INTEGER" };

/**
 * Construct an {@link Error Error} with the `"ERR_REDIS_INVALID_PASSWORD"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_REDIS_INVALID_PASSWORD"` in builtins.d.ts.
 */
declare function $ERR_REDIS_INVALID_PASSWORD(message: string): Error & { name: "RedisError", code: "ERR_REDIS_INVALID_PASSWORD" };

/**
 * Construct an {@link Error Error} with the `"ERR_REDIS_INVALID_RESPONSE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_REDIS_INVALID_RESPONSE"` in builtins.d.ts.
 */
declare function $ERR_REDIS_INVALID_RESPONSE(message: string): Error & { name: "RedisError", code: "ERR_REDIS_INVALID_RESPONSE" };

/**
 * Construct an {@link Error Error} with the `"ERR_REDIS_INVALID_RESPONSE_TYPE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_REDIS_INVALID_RESPONSE_TYPE"` in builtins.d.ts.
 */
declare function $ERR_REDIS_INVALID_RESPONSE_TYPE(message: string): Error & { name: "RedisError", code: "ERR_REDIS_INVALID_RESPONSE_TYPE" };

/**
 * Construct an {@link Error Error} with the `"ERR_REDIS_INVALID_SIMPLE_STRING"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_REDIS_INVALID_SIMPLE_STRING"` in builtins.d.ts.
 */
declare function $ERR_REDIS_INVALID_SIMPLE_STRING(message: string): Error & { name: "RedisError", code: "ERR_REDIS_INVALID_SIMPLE_STRING" };

/**
 * Construct an {@link Error Error} with the `"ERR_REDIS_INVALID_STATE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_REDIS_INVALID_STATE"` in builtins.d.ts.
 */
declare function $ERR_REDIS_INVALID_STATE(message: string): Error & { name: "RedisError", code: "ERR_REDIS_INVALID_STATE" };

/**
 * Construct an {@link Error Error} with the `"ERR_REDIS_INVALID_USERNAME"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_REDIS_INVALID_USERNAME"` in builtins.d.ts.
 */
declare function $ERR_REDIS_INVALID_USERNAME(message: string): Error & { name: "RedisError", code: "ERR_REDIS_INVALID_USERNAME" };

/**
 * Construct an {@link Error Error} with the `"ERR_REDIS_TLS_NOT_AVAILABLE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_REDIS_TLS_NOT_AVAILABLE"` in builtins.d.ts.
 */
declare function $ERR_REDIS_TLS_NOT_AVAILABLE(message: string): Error & { name: "RedisError", code: "ERR_REDIS_TLS_NOT_AVAILABLE" };

/**
 * Construct an {@link Error Error} with the `"ERR_REDIS_TLS_UPGRADE_FAILED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_REDIS_TLS_UPGRADE_FAILED"` in builtins.d.ts.
 */
declare function $ERR_REDIS_TLS_UPGRADE_FAILED(message: string): Error & { name: "RedisError", code: "ERR_REDIS_TLS_UPGRADE_FAILED" };

/**
 * Construct an {@link Error Error} with the `"HPE_UNEXPECTED_CONTENT_LENGTH"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"HPE_UNEXPECTED_CONTENT_LENGTH"` in builtins.d.ts.
 */
declare function $HPE_UNEXPECTED_CONTENT_LENGTH(message: string): Error & { code: "HPE_UNEXPECTED_CONTENT_LENGTH" };

/**
 * Construct an {@link Error Error} with the `"HPE_INVALID_TRANSFER_ENCODING"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"HPE_INVALID_TRANSFER_ENCODING"` in builtins.d.ts.
 */
declare function $HPE_INVALID_TRANSFER_ENCODING(message: string): Error & { code: "HPE_INVALID_TRANSFER_ENCODING" };

/**
 * Construct an {@link Error Error} with the `"HPE_INVALID_EOF_STATE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"HPE_INVALID_EOF_STATE"` in builtins.d.ts.
 */
declare function $HPE_INVALID_EOF_STATE(message: string): Error & { code: "HPE_INVALID_EOF_STATE" };

/**
 * Construct an {@link Error Error} with the `"HPE_INVALID_METHOD"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"HPE_INVALID_METHOD"` in builtins.d.ts.
 */
declare function $HPE_INVALID_METHOD(message: string): Error & { code: "HPE_INVALID_METHOD" };

/**
 * Construct an {@link Error Error} with the `"HPE_INTERNAL"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"HPE_INTERNAL"` in builtins.d.ts.
 */
declare function $HPE_INTERNAL(message: string): Error & { code: "HPE_INTERNAL" };

/**
 * Construct an {@link Error Error} with the `"ERR_VM_MODULE_CACHED_DATA_REJECTED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_VM_MODULE_CACHED_DATA_REJECTED"` in builtins.d.ts.
 */
declare function $ERR_VM_MODULE_CACHED_DATA_REJECTED(message: string): Error & { code: "ERR_VM_MODULE_CACHED_DATA_REJECTED" };

/**
 * Construct an {@link TypeError TypeError} with the `"ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING"` in builtins.d.ts.
 */
declare function $ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING(message: string): TypeError & { code: "ERR_VM_DYNAMIC_IMPORT_CALLBACK_MISSING" };

/**
 * Construct an {@link Error Error} with the `"HPE_INVALID_HEADER_TOKEN"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"HPE_INVALID_HEADER_TOKEN"` in builtins.d.ts.
 */
declare function $HPE_INVALID_HEADER_TOKEN(message: string): Error & { code: "HPE_INVALID_HEADER_TOKEN" };

/**
 * Construct an {@link Error Error} with the `"HPE_HEADER_OVERFLOW"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"HPE_HEADER_OVERFLOW"` in builtins.d.ts.
 */
declare function $HPE_HEADER_OVERFLOW(message: string): Error & { code: "HPE_HEADER_OVERFLOW" };

/**
 * Construct an {@link Error Error} with the `"ERR_SECRETS_NOT_AVAILABLE"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_SECRETS_NOT_AVAILABLE"` in builtins.d.ts.
 */
declare function $ERR_SECRETS_NOT_AVAILABLE(message: string): Error & { code: "ERR_SECRETS_NOT_AVAILABLE" };

/**
 * Construct an {@link Error Error} with the `"ERR_SECRETS_NOT_FOUND"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_SECRETS_NOT_FOUND"` in builtins.d.ts.
 */
declare function $ERR_SECRETS_NOT_FOUND(message: string): Error & { code: "ERR_SECRETS_NOT_FOUND" };

/**
 * Construct an {@link Error Error} with the `"ERR_SECRETS_ACCESS_DENIED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_SECRETS_ACCESS_DENIED"` in builtins.d.ts.
 */
declare function $ERR_SECRETS_ACCESS_DENIED(message: string): Error & { code: "ERR_SECRETS_ACCESS_DENIED" };

/**
 * Construct an {@link Error Error} with the `"ERR_SECRETS_PLATFORM_ERROR"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_SECRETS_PLATFORM_ERROR"` in builtins.d.ts.
 */
declare function $ERR_SECRETS_PLATFORM_ERROR(message: string): Error & { code: "ERR_SECRETS_PLATFORM_ERROR" };

/**
 * Construct an {@link Error Error} with the `"ERR_SECRETS_USER_CANCELED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_SECRETS_USER_CANCELED"` in builtins.d.ts.
 */
declare function $ERR_SECRETS_USER_CANCELED(message: string): Error & { code: "ERR_SECRETS_USER_CANCELED" };

/**
 * Construct an {@link Error Error} with the `"ERR_SECRETS_INTERACTION_NOT_ALLOWED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_SECRETS_INTERACTION_NOT_ALLOWED"` in builtins.d.ts.
 */
declare function $ERR_SECRETS_INTERACTION_NOT_ALLOWED(message: string): Error & { code: "ERR_SECRETS_INTERACTION_NOT_ALLOWED" };

/**
 * Construct an {@link Error Error} with the `"ERR_SECRETS_AUTH_FAILED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_SECRETS_AUTH_FAILED"` in builtins.d.ts.
 */
declare function $ERR_SECRETS_AUTH_FAILED(message: string): Error & { code: "ERR_SECRETS_AUTH_FAILED" };

/**
 * Construct an {@link Error Error} with the `"ERR_SECRETS_INTERACTION_REQUIRED"` error code.
 *
 * To override this, update ErrorCode.cpp. To remove this generated type, mention `"ERR_SECRETS_INTERACTION_REQUIRED"` in builtins.d.ts.
 */
declare function $ERR_SECRETS_INTERACTION_REQUIRED(message: string): Error & { code: "ERR_SECRETS_INTERACTION_REQUIRED" };
