#pragma once
// File generated via `create-hash-table.ts`
static constinit const struct CompactHashIndex nodeModuleObjectTableIndex[69] = {
    { -1, -1 },
    { 14, -1 },
    { -1, -1 },
    { -1, -1 },
    { 16, -1 },
    { -1, -1 },
    { 24, -1 },
    { -1, -1 },
    { 9, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 11, -1 },
    { -1, -1 },
    { 15, 66 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 13, 68 },
    { 20, -1 },
    { 3, -1 },
    { 17, -1 },
    { -1, -1 },
    { 7, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 0, 65 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 2, 67 },
    { -1, -1 },
    { -1, -1 },
    { 1, 64 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 12, -1 },
    { 21, -1 },
    { -1, -1 },
    { 8, -1 },
    { -1, -1 },
    { -1, -1 },
    { 22, -1 },
    { -1, -1 },
    { 10, -1 },
    { 25, -1 },
    { 23, -1 },
    { -1, -1 },
    { -1, -1 },
    { 4, -1 },
    { -1, -1 },
    { -1, -1 },
    { 27, -1 },
    { -1, -1 },
    { -1, -1 },
    { 5, -1 },
    { 6, -1 },
    { 18, -1 },
    { 19, -1 },
    { 26, -1 },
};

static constinit const struct HashTableValue nodeModuleObjectTableValues[28] = {
   { "_cache"_s, static_cast<unsigned>(PropertyAttribute::PropertyCallback), NoIntrinsic, { HashTableValue::LazyPropertyType, getModuleCacheObject } },
   { "_debug"_s, static_cast<unsigned>(PropertyAttribute::PropertyCallback), NoIntrinsic, { HashTableValue::LazyPropertyType, getModuleDebugObject } },
   { "_extensions"_s, static_cast<unsigned>(PropertyAttribute::PropertyCallback), NoIntrinsic, { HashTableValue::LazyPropertyType, getModuleExtensionsObject } },
   { "_findPath"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &jsFunctionFindPath, 3 } },
   { "_initPaths"_s, ((static_cast<unsigned>(PropertyAttribute::Function|PropertyAttribute::Builtin)) & ~PropertyAttribute::Function) | PropertyAttribute::Builtin, NoIntrinsic, { HashTableValue::BuiltinGeneratorType, nodeModuleObject_initPathsCodeGenerator, 0 } },
   { "_load"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &jsFunctionLoad, 1 } },
   { "_nodeModulePaths"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &Resolver__nodeModulePathsForJS, 1 } },
   { "_pathCache"_s, static_cast<unsigned>(PropertyAttribute::PropertyCallback), NoIntrinsic, { HashTableValue::LazyPropertyType, getPathCacheObject } },
   { "_preloadModules"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &jsFunctionPreloadModules, 0 } },
   { "_resolveFilename"_s, static_cast<unsigned>(PropertyAttribute::CustomAccessor), NoIntrinsic, { HashTableValue::GetterSetterType, nodeModuleResolveFilename, setNodeModuleResolveFilename } },
   { "_resolveLookupPaths"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &jsFunctionResolveLookupPaths, 2 } },
   { "_stat"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, Generated::NodeModuleModule::js_stat, 1 } },
   { "builtinModules"_s, static_cast<unsigned>(PropertyAttribute::PropertyCallback), NoIntrinsic, { HashTableValue::LazyPropertyType, getBuiltinModulesObject } },
   { "constants"_s, static_cast<unsigned>(PropertyAttribute::PropertyCallback), NoIntrinsic, { HashTableValue::LazyPropertyType, getConstantsObject } },
   { "createRequire"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &jsFunctionNodeModuleCreateRequire, 1 } },
   { "enableCompileCache"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &jsFunctionEnableCompileCache, 0 } },
   { "findSourceMap"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &Bun__JSSourceMap__find, 1 } },
   { "getCompileCacheDir"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &jsFunctionGetCompileCacheDir, 0 } },
   { "globalPaths"_s, static_cast<unsigned>(PropertyAttribute::PropertyCallback), NoIntrinsic, { HashTableValue::LazyPropertyType, getGlobalPathsObject } },
   { "isBuiltin"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &jsFunctionIsBuiltinModule, 1 } },
   { "prototype"_s, static_cast<unsigned>(PropertyAttribute::PropertyCallback), NoIntrinsic, { HashTableValue::LazyPropertyType, getModulePrototypeObject } },
   { "register"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &jsFunctionRegister, 1 } },
   { "runMain"_s, static_cast<unsigned>(PropertyAttribute::CustomAccessor), NoIntrinsic, { HashTableValue::GetterSetterType, moduleRunMain, setModuleRunMain } },
   { "SourceMap"_s, static_cast<unsigned>(PropertyAttribute::PropertyCallback), NoIntrinsic, { HashTableValue::LazyPropertyType, getSourceMapFunction } },
   { "syncBuiltinESMExports"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &jsFunctionSyncBuiltinESMExports, 0 } },
   { "wrap"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &jsFunctionWrap, 1 } },
   { "wrapper"_s, static_cast<unsigned>(PropertyAttribute::CustomAccessor), NoIntrinsic, { HashTableValue::GetterSetterType, nodeModuleWrapper, setNodeModuleWrapper } },
   { "Module"_s, static_cast<unsigned>(PropertyAttribute::PropertyCallback), NoIntrinsic, { HashTableValue::LazyPropertyType, getModuleObject } },
};

static constinit const struct HashTable nodeModuleObjectTable =
    { 28, 63, true, nullptr, nodeModuleObjectTableValues, nodeModuleObjectTableIndex };
