#pragma once
// File generated via `create-hash-table.ts`
static constinit const struct CompactHashIndex processBindingBufferTableIndex[73] = {
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 31, -1 },
    { -1, -1 },
    { 0, 66 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 11, 72 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 27, -1 },
    { -1, -1 },
    { 4, -1 },
    { 10, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 2, 64 },
    { 13, -1 },
    { 17, -1 },
    { -1, -1 },
    { 30, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 14, -1 },
    { 16, -1 },
    { 6, 67 },
    { 24, -1 },
    { 1, -1 },
    { -1, -1 },
    { 8, -1 },
    { 19, -1 },
    { -1, -1 },
    { 28, -1 },
    { -1, -1 },
    { 3, 65 },
    { -1, -1 },
    { 26, -1 },
    { 20, 70 },
    { -1, -1 },
    { 21, -1 },
    { -1, -1 },
    { -1, -1 },
    { -1, -1 },
    { 7, -1 },
    { 5, -1 },
    { 9, 68 },
    { 12, 69 },
    { 15, -1 },
    { 18, -1 },
    { 22, -1 },
    { 23, 71 },
    { 25, -1 },
    { 29, -1 },
};

static constinit const struct HashTableValue processBindingBufferTableValues[32] = {
   { "asciiSlice"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Buffer_asciiSlice, 1 } },
   { "asciiWriteStatic"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Buffer_asciiWriteStatic, 1 } },
   { "atob"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Buffer_atob, 1 } },
   { "base64Slice"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Buffer_base64Slice, 1 } },
   { "base64Write"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Buffer_base64Write, 1 } },
   { "base64urlSlice"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Buffer_base64urlSlice, 1 } },
   { "base64urlWrite"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Buffer_base64urlWrite, 1 } },
   { "btoa"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Buffer_btoa, 1 } },
   { "byteLengthUtf8"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Buffer_byteLengthUtf8, 1 } },
   { "compare"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Buffer_compare, 1 } },
   { "compareOffset"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Buffer_compareOffset, 1 } },
   { "copy"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Buffer_copy, 1 } },
   { "copyArrayBuffer"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Buffer_copyArrayBuffer, 1 } },
   { "detachArrayBuffer"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Buffer_detachArrayBuffer, 1 } },
   { "fill"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Buffer_fill, 1 } },
   { "getZeroFillToggle"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Buffer_getZeroFillToggle, 1 } },
   { "hexSlice"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Buffer_hexSlice, 1 } },
   { "hexWrite"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Buffer_hexWrite, 1 } },
   { "indexOfBuffer"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Buffer_indexOfBuffer, 1 } },
   { "indexOfNumber"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Buffer_indexOfNumber, 1 } },
   { "indexOfString"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Buffer_indexOfString, 1 } },
   { "isAscii"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Buffer_isAscii, 1 } },
   { "isUtf8"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Buffer_isUtf8, 1 } },
   { "latin1Slice"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Buffer_latin1Slice, 1 } },
   { "latin1WriteStatic"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Buffer_latin1WriteStatic, 1 } },
   { "swap16"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Buffer_swap16, 1 } },
   { "swap32"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Buffer_swap32, 1 } },
   { "swap64"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Buffer_swap64, 1 } },
   { "ucs2Slice"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Buffer_ucs2Slice, 1 } },
   { "ucs2Write"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Buffer_ucs2Write, 1 } },
   { "utf8Slice"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Buffer_utf8Slice, 1 } },
   { "utf8WriteStatic"_s, static_cast<unsigned>(PropertyAttribute::Function), NoIntrinsic, { HashTableValue::NativeFunctionType, &ProcessBinding_Buffer_utf8WriteStatic, 1 } },
};

static constinit const struct HashTable processBindingBufferTable =
    { 32, 63, false, nullptr, processBindingBufferTableValues, processBindingBufferTableIndex };
